export const People=[
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    }
]

export const BuisnessBill=[
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    }
]

export const billType=[
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
   
]

export const promotions=[
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
   
]