export const People=[
    {
        index:1,
        profile:require("../assets/user1.jpeg"),
        name:"User1"
    },
    {
        index:2,
        profile:require("../assets/user2.jpeg"),
        name:"User2"
    },
    {
        index:3,
        profile:require("../assets/user3.jpeg"),
        name:"User3"
    },
    {
        index:4,
        profile:require("../assets/user9.jpeg"),
        name:"User4"
    },
    {
        index:5,
        profile:require("../assets/user7.jpeg"),
        name:"Monu"
    },
    {
        index:6,
        profile:require("../assets/user5.jpeg"),
        name:"User5"
    },
    {
        index:7,
        profile:require("../assets/user6.jpeg"),
        name:"User6"
    },
    {
        index:8,
        profile:require("../assets/user7.jpeg"),
        name:"User7"
    },
    {
        index:9,
        profile:require("../assets/user8.jpeg"),
        name:"User8"
    },
    {
        index:10,
        profile:require("../assets/user9.jpeg"),
        name:"User9"
    },
    {
        index:11,
        profile:require("../assets/user1.jpeg"),
        name:"User10"
    },
    {
        index:12,
        profile:require("../assets/user2.jpeg"),
        name:"User12"
    },
    {
        index:13,
        profile:require("../assets/user3.jpeg"),
        name:"Ueser13"
    },
    {
        index:14,
        profile:require("../assets/user9.jpeg"),
        name:"User14"
    },
    {
        index:15,
        profile:require("../assets/user5.jpeg"),
        name:"User15"
    }
]

export const BuisnessBill=[
    {
        index:1,
        profile:require("../assets/bill.png"),
        name:"Bill"
    },
    {
        index:2,
        profile:require("../assets/recharge.png"),
        name:"Recharge"
    },
    {
        index:3,
        profile:require("../assets/spots.png"),
        name:"Spots"
    },
    {
        index:4,
        profile:require("../assets/donation.png"),
        name:"Donations"
    },
    {
        index:5,
        profile:require("../assets/gold.png"),
        name:"Gold"
    },
    {
        index:6,
        profile:require("../assets/icon.png"),
        name:"Monu"
    },
    {
        index:7,
        profile:require("../assets/icon.png"),
        name:"Monu"
    }
]

export const billType=[
    {
        index:1,
        profile:require("../assets/jio.png"),
        name:"Jio"
    },
    {
        index:2,
        profile:require("../assets/mahanagr.jpeg"),
        name:"Mahanagar"
    },
    {
        index:3,
        profile:require("../assets/vodaphone.jpg"),
        name:"Idea"
    },
    {
        index:4,
        profile:require("../assets/5paise.jpeg"),
        name:"Paisa"
    },
    {
        index:5,
        profile:require("../assets/vodafone1.jpeg"),
        name:"Voda fone"
    },
    {
        index:6,
        profile:require("../assets/swiggy.png"),
        name:"Swiggy"
    },
    {
        index:7,
        profile:require("../assets/zomato.png"),
        name:"Zomato"
    },
    {
        index:8,
        profile:require("../assets/icon.png"),
        name:"Vodalfone "
    },
    {
        index:9,
        profile:require("../assets/jio.png"),
        name:"Jio"
    },
    {
        index:10,
        profile:require("../assets/mahanagr.jpeg"),
        name:"Mahanagar"
    },
    {
        index:11,
        profile:require("../assets/5paise.jpeg"),
        name:"Paisa"
    },
    {
        index:12,
        profile:require("../assets/vodaphone.jpg"),
        name:"Idea"
    },
   
]

export const promotions=[
    {
        index:1,
        profile:require("../assets/reward.jpeg"),
        name:"Rewards "
    },
    {
        index:2,
        profile:require("../assets/Offers.png"),
        name:"Offers"
    },
    {
        index:3,
        profile:require("../assets/referal.png"),
        name:"Referals"
    },
   
]